### ISSUE TITLE
Route 404 accuses sentry error

### ISSUE THREAD

**Issue by paulocastellano** [Perafan18/adonis-sentry#10]
- Sentry Provider Version: 2.0.2
- Node Version: 8.12.0
- NPM Version: 6.4.1
- OS: Mac

### Description:
If you access a route that does not exist, it catches the error .... is there a way to ignore it?
Why a 404 page is not necessarily a error.

**Example**:
E_ROUTE_NOT_FOUND: Route not found GET /api/projects/my-project-id/invalid-route

**Comment by dguzman1012** [comment]
The best way to do that is just to determinate the error status:

![image](https://user-images.githubusercontent.com/5767551/73188755-1d90f280-4102-11ea-8722-2c924e7c894b.png)

**Comment by paulocastellano** [comment]
Thanks for help!
